# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 1e7b96b967c73bf7f81b6fdf942962407d92c09a7be18d08ec306417656fb4d9b2f0196e3f942dbed57a6d4f3f7fa3820bee83c54239dd8dd54da97815f3171c

staging:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

test:
  secret_key_base: 617a5ae9cbed6a36bbd518bd8fbcf7f3afe229581834f67f4df6dd1f530810a85b5d5af132e59f86ef3d0059c97e10107e5c6c9130fb3eaa24361a6920a4b37a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
